"""add image enhancement jobs

Revision ID: cbb17fb314a0
Revises: b1d98f866ab5
Create Date: 2026-09-19 14:19:30.577692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = 'cbb17fb314a0'
down_revision: Union[str, Sequence[str], None] = 'b1d98f866ab5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('source_image_id', sa.Uuid(), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=32), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.String(length=1024), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_image_id'], ['images.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_path')
    )
    op.create_index(op.f('ix_images_source_image_id'), 'images', ['source_image_id'], unique=False)
    op.create_index(op.f('ix_images_user_id'), 'images', ['user_id'], unique=False)
    op.create_table('enhancement_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('input_image_id', sa.Uuid(), nullable=False),
    sa.Column('result_image_id', sa.Uuid(), nullable=True),
    sa.Column('scale_factor', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'PROCESSING', 'COMPLETED', 'FAILED', name='enhancement_job_status'), nullable=False),
    sa.Column('queued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['input_image_id'], ['images.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['result_image_id'], ['images.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enhancement_jobs_input_image_id'), 'enhancement_jobs', ['input_image_id'], unique=False)
    op.create_index(op.f('ix_enhancement_jobs_result_image_id'), 'enhancement_jobs', ['result_image_id'], unique=False)
    op.create_index(op.f('ix_enhancement_jobs_status'), 'enhancement_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_enhancement_jobs_user_id'), 'enhancement_jobs', ['user_id'], unique=False)
    op.create_table('processing_metadata',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('model_version', sa.String(length=128), nullable=False),
    sa.Column('scale_factor', sa.Integer(), nullable=False),
    sa.Column('input_width', sa.Integer(), nullable=False),
    sa.Column('input_height', sa.Integer(), nullable=False),
    sa.Column('output_width', sa.Integer(), nullable=True),
    sa.Column('output_height', sa.Integer(), nullable=True),
    sa.Column('processing_time_ms', sa.Float(), nullable=True),
    sa.Column('device', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['enhancement_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processing_metadata_job_id'), 'processing_metadata', ['job_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_processing_metadata_job_id'), table_name='processing_metadata')
    op.drop_table('processing_metadata')
    op.drop_index(op.f('ix_enhancement_jobs_user_id'), table_name='enhancement_jobs')
    op.drop_index(op.f('ix_enhancement_jobs_status'), table_name='enhancement_jobs')
    op.drop_index(op.f('ix_enhancement_jobs_result_image_id'), table_name='enhancement_jobs')
    op.drop_index(op.f('ix_enhancement_jobs_input_image_id'), table_name='enhancement_jobs')
    op.drop_table('enhancement_jobs')
    sa.Enum(
        'QUEUED',
        'PROCESSING',
        'COMPLETED',
        'FAILED',
        name='enhancement_job_status',
    ).drop(op.get_bind(), checkfirst=True)
    op.drop_index(op.f('ix_images_user_id'), table_name='images')
    op.drop_index(op.f('ix_images_source_image_id'), table_name='images')
    op.drop_table('images')
    # ### end Alembic commands ###
